Repository luminosityleds/server, pull requests merged in 2022-12, with the labels that each got.

#19 LL-82
  client/package-lock.json
  client/package.json
  client/src/components/Login.tsx
  client/src/css/Login.css
Labels: bug

#13 LL-23: Setup documentation for python code
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/sphinx_documentation.yml
  controller/README.md
  controller/pylintrc
  controller/requirements.txt
  doc_mds/README.md
  doc_mds/sequence_diagram/embedded.md
  doc_mds/sequence_diagram/web_app.md
  docs/build/html/.buildinfo
  docs/build/html/.doctrees/environment.pickle
  docs/build/html/.doctrees/index.doctree
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  docs/build/html/_static/basic.css
  docs/build/html/_static/css/badge_only.css
  docs/build/html/_static/css/fonts/Roboto-Slab-Bold.woff
  docs/build/html/_static/css/fonts/Roboto-Slab-Bold.woff2
  docs/build/html/_static/css/fonts/Roboto-Slab-Regular.woff
  docs/build/html/_static/css/fonts/Roboto-Slab-Regular.woff2
  docs/build/html/_static/css/fonts/fontawesome-webfont.eot
  docs/build/html/_static/css/fonts/fontawesome-webfont.svg
  docs/build/html/_static/css/fonts/fontawesome-webfont.ttf
  docs/build/html/_static/css/fonts/fontawesome-webfont.woff
  docs/build/html/_static/css/fonts/fontawesome-webfont.woff2
  docs/build/html/_static/css/fonts/lato-bold-italic.woff
  docs/build/html/_static/css/fonts/lato-bold-italic.woff2
  docs/build/html/_static/css/fonts/lato-bold.woff
  docs/build/html/_static/css/fonts/lato-bold.woff2
  docs/build/html/_static/css/fonts/lato-normal-italic.woff
  docs/build/html/_static/css/fonts/lato-normal-italic.woff2
  docs/build/html/_static/css/fonts/lato-normal.woff
  docs/build/html/_static/css/fonts/lato-normal.woff2
  docs/build/html/_static/css/theme.css
  docs/build/html/_static/doctools.js
  docs/build/html/_static/documentation_options.js
  docs/build/html/_static/file.png
  docs/build/html/_static/jquery-3.6.0.js
  docs/build/html/_static/jquery.js
  docs/build/html/_static/js/badge_only.js
  docs/build/html/_static/js/html5shiv-printshiv.min.js
  docs/build/html/_static/js/html5shiv.min.js
  docs/build/html/_static/js/theme.js
  docs/build/html/_static/language_data.js
  docs/build/html/_static/minus.png
  docs/build/html/_static/plus.png
  docs/build/html/_static/pygments.css
  docs/build/html/_static/searchtools.js
  docs/build/html/_static/sphinx_highlight.js
  docs/build/html/_static/underscore-1.13.1.js
  docs/build/html/_static/underscore.js
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#23 LL-85
  client/src/components/Header.tsx
  client/src/components/Login.tsx
  client/src/components/Register.tsx
  client/src/css/App.css
  client/src/css/Login.css
  client/src/css/README.md
  client/src/css/Register.css
  client/tsconfig.json
  markdown/README.md
  markdown/sequence_diagram/embedded.md
  markdown/sequence_diagram/web_app.md
Labels: account

#24 LL-86
  .github/workflows/mongodb_connect.yml
  .github/workflows/pylint.yml
  .vscode/extensions.json
  server/README.md
  server/src/index.ts
Labels: mongodb

#25 LL-89
  client/public/images/luminosity-home-logo.ico
  client/src/components/Header.tsx
  client/src/css/App.css
  client/src/imgs/luminosity-home-logo.png
Labels: bug

#27 LL-97
  .github/workflows/luminosityleds_update.yml
  .github/workflows/mongodb_connect.yml
  .github/workflows/pylint.yml
  client/README.md
  client/package.json
  client/public/CNAME
  client/public/images/luminosity-home-logo.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/imgs/luminosity-home-logo.png
  client/src/index.js
Labels: account

#28 LL-99
  client/README.md
  client/public/index.html
Labels: bug

#30 LL-104
  client/src/components/Header.tsx
  client/src/css/App.css
Labels: bug
