Repository luminosityleds/server, pull requests merged in 2023-01, with the labels that each got.

#31 LL-102
  .github/workflows/luminosityleds_update.yml
  .github/workflows/pylint.yml
  scripts/.gitignore
  scripts/README.md
  scripts/create_jira_release_notes.py
  scripts/pylintrc
  scripts/requirements.txt
Labels: cicd

#32 LL-103
  .vscode/extensions.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Login.tsx
  client/src/css/App.css
  client/src/css/README.md
Labels: enhancement

#17 LL-27 mcu change brightness and color
  .gitignore
  controller/.gitignore
  controller/README.md
  controller/helloWorld.py
  controller/requirements.txt
  controller/src/boot.py
  controller/src/lighting_unit.py
  controller/src/main.py
Labels: embedded

#33 LL-111
  client/src/css/App.css
Labels: UX

#35 LL-98
  client/src/css/App.css
  client/src/css/README.md
Labels: UX

#34 LL-29
  controller/README.md
Labels: embedded

#36 LL-112
  client/src/components/Footer.tsx
  client/src/css/App.css
Labels: UX

#37 LL-114
  client/src/css/App.css
  scripts/create_jira_release_notes.py
Labels: bug

#38 LL-94:
  client/package-lock.json
  client/package.json
  client/src/components/Login.tsx
  client/src/components/Register.tsx
  client/src/components/ThirdParty.tsx
  client/src/css/App.css
  server/src/index.ts
  server/src/models/UserSchema.ts
  server/src/routes/routes.ts
Labels: UX

#40 LL-76: Create Account
  client/src/components/Header.tsx
  client/src/components/README.md
  client/src/components/ThirdParty.tsx
  client/src/css/App.css
  mongodb/Schema/AccountSchema.json
  mongodb/Schema/README.md
  server/package.json
  server/src/README.md
  server/src/index.ts
  server/src/models/UserSchema.ts
  server/src/routes/routes.ts
  server/src/server.ts
  server/test.http
Labels: account

#42 LL-95: added microsoft sso config files
  client/package-lock.json
  client/package.json
  client/src/components/ThirdParty.tsx
  server/.gitignore
Labels: help wanted, account

#44 LL-129: Remove apple SSO login and register btns
  client/src/components/Login.tsx
  client/src/components/README.md
  client/src/components/Register.tsx
  client/src/components/ThirdParty.tsx
Labels: account, UX

#21 Adding base code for brightness and color changes.
  .github/workflows/pylint.yml
  .gitignore
  controller/pylintrc
  controller/src/board/lights.py
  controller/src/board/wlan.py
  controller/test/__init__.py
  controller/test/mpstubs.py
  controller/test/test_readLights.py
  controller/test/test_waln.py
Labels: embedded
